---
- name: Ensure localhost in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1.*"
    line: "127.0.0.1 localhost"
    state: present
  become: True
  when: customize_etc_hosts | bool

- name: Ensure hostnames does not point to 127.0.1.1 in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1\\b.*\\s{{ ansible_hostname }}\\b"
    state: absent
  become: True
  when: customize_etc_hosts | bool

- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {% for host in group['baremetal'] %}
        {% set api_interface = hostvars[host]['api_interface'] %}
        {% endfor %}
  when:
    - customize_etc_hosts | bool

- name: Check whether cloud-init has been installed, and ensure manage_etc_hosts is disabled

  